repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-toml
      - id: check-yaml

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: python
        types: [python]
        additional_dependencies: ["pyright==1.1.377"]
        stages: [pre-commit]

      # Run full repo checks before push to mirror CI behavior
      - id: repo-check
        name: repo-check (ruff format/check + pyright)
        language: system
        entry: bash -lc 'mise run check'
        pass_filenames: false
        stages: [pre-push]
