name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up mise and install tools
        uses: jdx/mise-action@v2
        with:
          version: 'latest'
          install: true

      - name: Install dependencies (frozen)
        run: mise run setup

      - name: Format + Lint + Type-check
        run: mise run check

      - name: Tests
        run: mise run test
