name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install mise
        run: |
          curl -fsSL https://mise.jdx.dev/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install tools via mise
        run: mise install

      - name: Install dependencies
        run: mise run --frozen setup

      - name: Format + Lint + Type-check
        run: mise run check

      - name: Tests
        run: mise run test
